### ISSUE TITLE
Calls to `require` must appear at the top-level

### ISSUE THREAD

**Issue by shlomi-dr** [cjohansen/courier#6]
For some reason this works fine in Clojure, but in ClojureScript this line

https://github.com/cjohansen/courier/blob/99a77471ed6b9c37831d41a6e58ae7de0b3ee071/src/courier/cache.cljc#L147

barfs with the following:

```
Calls to `require` must appear at the top-level. at line 147
   file:/Users/shlomi/.m2/repository/cjohansen/courier/2023.02.17/courier-2023.02.17.jar!/courier/cache.cljc
   {:file
    "file:/Users/shlomi/.m2/repository/cjohansen/courier/2023.02.17/courier-2023.02.17.jar!/courier/cache.cljc",
    :line 147,
    :column 5,
    :tag :cljs/analysis-error}
```

**Comment by cjohansen** [comment]
Interesting. Does carmine even work on cljs? If not, this can be solved with a reader conditional.

**Comment by cjohansen** [comment]
There's no reason it can't work on ClojureScript, but I've only used it in Clojure myself. I'll make it load on cljs at least 😅
